// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    BadgeEvents: typeof import('./components/TelaHome/TelaAgendador/BadgeEvents.vue')['default']
    CalendarSalao: typeof import('./components/TelaHome/TelaAgendador/CalendarSalao.vue')['default']
    CardDate: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/CardDate.vue')['default']
    CardPermissoes: typeof import('./components/TelaPermissoes/CardPermissoes.vue')['default']
    CardTime: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/CardTime.vue')['default']
    CommonModal: typeof import('./components/CommonModal.vue')['default']
    ContentSection: typeof import('./components/ContentSection.vue')['default']
    DeleteButton: typeof import('./components/buttons/DeleteButton.vue')['default']
    DrawherMenu: typeof import('./components/TelaHome/DrawherMenu.vue')['default']
    DropDown: typeof import('./components/buttons/DropDown.vue')['default']
    FabButton: typeof import('./components/buttons/FabButton.vue')['default']
    HeaderCard: typeof import('./components/HeaderCard.vue')['default']
    HeaderHome: typeof import('./components/TelaHome/HeaderHome.vue')['default']
    Home: typeof import('./components/TelaHome/Home.vue')['default']
    InputDateTime: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/InputDateTime.vue')['default']
    InputsOfAgendamento: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/InputsOfAgendamento.vue')['default']
    InputTime: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/InputTime.vue')['default']
    ListMoradores: typeof import('./components/TelaListaMoradores/ListMoradores.vue')['default']
    LoaderButton: typeof import('./components/buttons/LoaderButton.vue')['default']
    MakdownEditor: typeof import('./components/MakdownEditor.vue')['default']
    ModalAgendarAdd: typeof import('./components/TelaHome/TelaAgendador/AddAgendamento/ModalAgendarAdd.vue')['default']
    MonthNavigation: typeof import('./components/TelaHome/TelaAgendador/Month/MonthNavigation.vue')['default']
    MontVisualization: typeof import('./components/TelaHome/TelaAgendador/Month/MontVisualization.vue')['default']
    OptionLocales: typeof import('./components/OptionLocales.vue')['default']
    PaymentButton: typeof import('./components/buttons/PaymentButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendButton: typeof import('./components/buttons/SendButton.vue')['default']
    TableO: typeof import('./components/TelaPermissoes/TableO.vue')['default']
    TablePermissoes: typeof import('./components/TelaPermissoes/TablePermissoes.vue')['default']
    ThemeButton: typeof import('./components/buttons/ThemeButton.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    TranslationComponent: typeof import('./components/TranslationComponent.vue')['default']
  }
}
